export const OK_TRANSACTION_ERROR = 'OK_TRANSACTION_ERROR'
export const OK_TRANSACTION = 'OK_TRANSACTION'
export const REMOVE_TRANSACTION_ERROR = 'REMOVE_TRANSACTION_ERROR'
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION'
export const ADD_USERS_TO_OVERVIEW = 'ADD_USERS_TO_OVERVIEW'
export const ADD_CREDITS_TO_OVERVIEW = 'ADD_CREDITS_TO_OVERVIEW'

export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS'
export const VERIFY_EMAIL = 'VERIFY_EMAIL'

export const FLAG_SLOT_INFO_TO_EXIT = 'FLAG_SLOT_INFO_TO_EXIT'

export const USER_AGENT = 'USER_AGENT'

export const ACTIVATE_SLOT  = 'ACTIVATE_SLOT'
export const ACTIVATION_FAILED  = 'ACTIVATION_FAILED'
export const CANCEL_SLOT  = 'CANCEL_SLOT'
export const SLOT_CANCEL_ERROR  = 'SLOT_CANCEL_ERROR'

export const SIGN_OUT = 'SIGN_OUT'
export const REGISTER_USER = 'REGISTER_USER'

export const BOOK_A_SLOT = 'BOOK_A_SLOT'
export const LATE_BOOK_A_SLOT = 'LATE_BOOK_A_SLOT'
export const BOOKING_ERROR = 'BOOKING_ERROR'
export const CANCEL_ERROR = 'CANCEL_ERROR'
export const CANCEL_RESERVATION = 'CANCEL_RESERVATION'

export const SEND_FEEDBABCK = 'SEND_FEEDBABCK'
export const CONFIGURE_DIAGNOSTICS = 'CONFIGURE_DIAGNOSTICS'
export const FLUSH_DIAGNOSTICS = 'FLUSH_DIAGNOSTICS'
export const FETCH_DIAGNOSTICS = 'FETCH_DIAGNOSTICS'
export const DO_PURCHASE_TRANSACTION = 'DO_PURCHASE_TRANSACTION'

export const CHECKOUT_ERROR = 'CHECKOUT_ERROR'
export const CHECKOUT_TIMEOUT = 'CHECKOUT_TIMEOUT'
export const START_CHECKOUT_FLOW = 'START_CHECKOUT_FLOW'
export const BUY_WITH_CASH = 'BUY_WITH_CASH'
export const BUY_DELAYED = 'BUY_DELAYED'
export const BUY_WITH_PAYTRAIL = 'BUY_WITH_PAYTRAIL'
export const FINISH_WITH_PAYTRAIL = 'FINISH_WITH_PAYTRAIL'
export const GET_AUTH_CODE = 'GET_AUTH_CODE'
export const EXECUTE_CASH_PURCHASE = 'EXECUTE_CASH_PURCHASE'

export const FETCH_PENDING_TRANSACTIONS = 'FETCH_PENDING_TRANSACTIONS'

export const FETCH_TERMS = 'FETCH_TERMS'

export const FETCH_SHOP_ITEMS = 'FETCH_SHOP_ITEMS'
export const RESET_SHOP = 'RESET_SHOP'

export const FETCH_TIMETABLE_BOOKINGS = 'FETCH_TIMETABLE_BOOKINGS'
export const FETCH_TIMETABLE = 'FETCH_TIMETABLE'

export const ADD_TO_CART = 'ADD_TO_CART'

export const CHANGE_LOADINGSCREEN_STATE = 'CHANGE_LOADINGSCREEN_STATE'

export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_TIMEOUT = 'AUTH_TIMEOUT'
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED'
export const EMAIL_UPDATED = 'EMAIL_UPDATED'
export const PASSWORD_RESET = 'PASSWORD_RESET'

export const USER_DETAILS_UPDATED_IN_DB = 'USER_DETAILS_UPDATED_IN_DB'
export const STOP_UPDATING_USER_DETAILS_FROM_DB = 'STOP_UPDATING_USER_DETAILS_FROM_DB'
export const USER_ERROR = 'USER_ERROR'
export const UPDATE_USERS_TRANSACTIONS = 'UPDATE_USERS_TRANSACTIONS'
export const UPDATE_USERS_BOOKINGS = 'UPDATE_USERS_BOOKINGS'

export const PUT_SLOT_INFO = 'PUT_SLOT_INFO'
export const FETCH_SLOT_BOOKINGS = 'FETCH_SLOT_BOOKINGS'
export const REMOVE_SLOT_INFO = 'REMOVE_SLOT_INFO'

export const FETCH_USER_LIST = 'FETCH_USER_LIST'
export const FETCH_ADMIN_LIST = 'FETCH_ADMIN_LIST'
export const FETCH_SLOT_LIST = 'FETCH_SLOT_LIST'
export const FETCH_SHOP_LIST = 'FETCH_SHOP_LIST'
export const FETCH_TERMS_LIST = 'FETCH_TERMS_LIST'
export const STOP_FETCH_TERMS_LIST = 'STOP_FETCH_TERMS_LIST'
export const FETCH_INFO_LIST = 'FETCH_INFO_LIST'
export const STOP_FETCH_INFO_LIST = 'STOP_FETCH_INFO_LIST'
export const STOP_FETCH_SHOP_LIST = 'STOP_FETCH_SHOP_LIST'

export const EXPAND_ADMIN_LIST = 'EXPAND_ADMIN_LIST'
export const MINIMIZE_ADMIN_LIST = 'MINIMIZE_ADMIN_LIST'
export const EXPAND_USER_LIST = 'EXPAND_USER_LIST'
export const MINIMIZE_USER_LIST = 'MINIMIZE_USER_LIST'
export const EXPAND_SLOT_LIST = 'EXPAND_SLOT_LIST'
export const MINIMIZE_SLOT_LIST = 'MINIMIZE_SLOT_LIST'
export const EXPAND_SHOP_LIST = 'EXPAND_SHOP_LIST'
export const MINIMIZE_SHOP_LIST = 'MINIMIZE_SHOP_LIST'

export const EXPAND_SLOT_FORM = 'EXPAND_SLOT_FORM'
export const MINIMIZE_SLOT_FORM = 'MINIMIZE_SLOT_FORM'
export const EXPAND_COUNT_SHOP_FORM = 'EXPAND_COUNT_SHOP_FORM'
export const MINIMIZE_COUNT_SHOP_FORM = 'MINIMIZE_COUNT_SHOP_FORM'
export const EXPAND_INFO_LIST = 'EXPAND_INFO_LIST'
export const MINIMIZE_INFO_LIST = 'MINIMIZE_INFO_LIST'
export const EXPAND_INFO_FORM = 'EXPAND_INFO_FORM'
export const MINIMIZE_INFO_FORM = 'MINIMIZE_INFO_FORM'
export const EXPAND_TERMS_LIST = 'EXPAND_TERMS_LIST'
export const MINIMIZE_TERMS_LIST = 'MINIMIZE_TERMS_LIST'
export const EXPAND_TERMS_FORM = 'EXPAND_TERMS_FORM'
export const MINIMIZE_TERMS_FORM = 'MINIMIZE_TERMS_FORM'

export const CHANGE_SEARCH_BAR = 'CHANGE_SEARCH_BAR'
